// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZLGC4sNCTUQRJf1S3vyIQ3hAQjwQGfJM',
    appId: '1:482181006889:web:e968bbe631651e25497e38',
    messagingSenderId: '482181006889',
    projectId: 'qube-analytics-sdk',
    authDomain: 'qube-analytics-sdk.firebaseapp.com',
    storageBucket: 'qube-analytics-sdk.appspot.com',
    measurementId: 'G-X5TQ51EHLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4TgKOZCqI6RkABEXgATnHQ1KjV89Cj9I',
    appId: '1:482181006889:android:e6958b25f529984d497e38',
    messagingSenderId: '482181006889',
    projectId: 'qube-analytics-sdk',
    storageBucket: 'qube-analytics-sdk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlKHVBh173tXtqc0HxhT_qrTHTE6OpGUQ',
    appId: '1:482181006889:ios:f17c8faa01b459be497e38',
    messagingSenderId: '482181006889',
    projectId: 'qube-analytics-sdk',
    storageBucket: 'qube-analytics-sdk.appspot.com',
    iosBundleId: 'com.exa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlKHVBh173tXtqc0HxhT_qrTHTE6OpGUQ',
    appId: '1:482181006889:ios:120fe49a2cbeea4d497e38',
    messagingSenderId: '482181006889',
    projectId: 'qube-analytics-sdk',
    storageBucket: 'qube-analytics-sdk.appspot.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZLGC4sNCTUQRJf1S3vyIQ3hAQjwQGfJM',
    appId: '1:482181006889:web:c7bfff782f99d1aa497e38',
    messagingSenderId: '482181006889',
    projectId: 'qube-analytics-sdk',
    authDomain: 'qube-analytics-sdk.firebaseapp.com',
    storageBucket: 'qube-analytics-sdk.appspot.com',
    measurementId: 'G-LLHQM84T7J',
  );
}
